FROM maven:3.9.9-eclipse-temurin-21
RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libnss3 libnspr4 libdbus-1-3 libatk1.0-0 \
    libatk-bridge2.0-0 libcups2 libdrm2 libxcb1 libxkbcommon0 \
    libatspi2.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 \
    libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 \
    libasound2 libxshmfence1 libx11-xcb1 libxcursor1 libxi6 \
    libgtk-3-0 libgdk-pixbuf2.0-0 libxrender1 libdbus-glib-1-2 && \
    rm -rf /var/lib/apt/lists/*